/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH
 * under one or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information regarding copyright
 * ownership. Camunda licenses this file to you under the Apache License,
 * Version 2.0; you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.camunda.connector.runtime.core.secret;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Function;
import java.util.regex.MatchResult;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/** Utility class to replace secrets in strings. */
public class SecretUtil {

  private static final Pattern SECRET_PATTERN_SECRETS =
      Pattern.compile("secrets\\.(?<secret>([a-zA-Z0-9]+[\\/._-])*[a-zA-Z0-9]+)");

  private static final Pattern SECRET_PATTERN_PARENTHESES =
      Pattern.compile("\\{\\{\\s*secrets\\.(?<secret>\\S+?\\s*)}}");

  // The exact character class SECRET_PATTERN_SECRETS captures. A bracketed name outside it (e.g.
  // containing ':') is truncated by the bare pattern's own narrower match -- see
  // replaceSecretsWithoutParentheses below.
  private static final Pattern BARE_SECRET_NAME =
      Pattern.compile("([a-zA-Z0-9]+[\\/._-])*[a-zA-Z0-9]+");

  public static String replaceSecrets(String input, Function<String, String> secretReplacer) {
    if (input == null) {
      throw new IllegalStateException("input cant be null.");
    }
    // Shared across both passes so that a name resolved (or denied) while scanning brackets is
    // never looked up again for the bare-pass denial check below -- secretReplacer is not
    // guaranteed side-effect-free in production (a provider aggregator can count each resolution),
    // so a name must be asked for at most once per call, whichever pass asks first.
    Map<String, String> resolutionsByName = new HashMap<>();
    input = replaceSecretsWithParentheses(input, secretReplacer, resolutionsByName);
    input = replaceSecretsWithoutParentheses(input, secretReplacer, resolutionsByName);
    return input;
  }

  private static String replaceSecretsWithParentheses(
      String input,
      Function<String, String> secretReplacer,
      Map<String, String> resolutionsByName) {
    var secretVariableNameWithParenthesesMatcher = SECRET_PATTERN_PARENTHESES.matcher(input);
    while (secretVariableNameWithParenthesesMatcher.find()) {
      input =
          replaceTokens(
              input,
              SECRET_PATTERN_PARENTHESES,
              matcher -> resolveSecretValue(secretReplacer, matcher, resolutionsByName));
    }
    return input;
  }

  // A chain-generated truncating bracket can itself resolve to another truncating bracket (e.g.
  // A -> {{secrets.B:C}} -> {{secrets.D:E}} -> FULL_VALUE). A single pass over the text only
  // resolves one such hop, leaving a deeper one to be wrongly bare-scanned below. A small, fixed
  // cap -- not derived from input size, which would hand an attacker a knob -- guards a value that
  // resolves to a bracketed reference of itself or a cycle through several names: resolutionsByName
  // memoizes by name, so a cycle reproduces byte-identical text every pass and never converges on
  // its own. No legitimate provider chain needs anywhere near this many hops.
  private static final int MAX_TRUNCATING_BRACKET_CHAIN_DEPTH = 10;

  /**
   * A bracketed reference still present in the text at this point -- whether from the original
   * input or generated by a chained resolution above -- has its own full name. When that name
   * contains a character the bare pattern's narrower class does not (e.g. {@code :}), the bare
   * pattern would only ever match a truncated prefix of it: a different name than the bracket
   * declares. Resolving that prefix independently either discards a successful full-name
   * resolution's actual value in favor of the prefix's own, or bypasses a denial of the full name
   * via an allowed prefix. Such a bracket is resolved by its own full name directly, consuming the
   * whole bracketed span, before the bare pattern ever touches it. A bracket whose full name is
   * entirely bare-pattern-safe needs none of this: resolving the (identical) bare match already
   * gives the correct result, so it is left for the scan below.
   */
  private static String replaceSecretsWithoutParentheses(
      String input,
      Function<String, String> secretReplacer,
      Map<String, String> resolutionsByName) {
    var secretVariableNameWithParenthesesMatcher = SECRET_PATTERN_SECRETS.matcher(input);
    while (secretVariableNameWithParenthesesMatcher.find()) {
      input = resolveTruncatingBracketsFully(input, secretReplacer, resolutionsByName);

      List<MatchResult> deniedBracketedReferences =
          SECRET_PATTERN_PARENTHESES
              .matcher(input)
              .results()
              .filter(
                  match ->
                      isTruncatedByBarePattern(match)
                          && isDenied(match, secretReplacer, resolutionsByName))
              .toList();
      // Both this list and the bare matches replaceTokens visits below are already left-to-right
      // ordered (Matcher.find()/results() guarantee it), and denied brackets never overlap. A
      // single forward cursor -- rather than rescanning the whole list per bare match -- keeps
      // this pass linear in the number of matches; without it, this loop itself reruns once per
      // original bare match, turning a quadratic-per-pass scan cubic overall for a payload with
      // many denied special-character references.
      int[] cursor = {0};
      input =
          replaceTokens(
              input,
              SECRET_PATTERN_SECRETS,
              matcher -> {
                while (cursor[0] < deniedBracketedReferences.size()
                    && deniedBracketedReferences.get(cursor[0]).end() <= matcher.start()) {
                  cursor[0]++;
                }
                boolean nested =
                    cursor[0] < deniedBracketedReferences.size()
                        && matcher.start() >= deniedBracketedReferences.get(cursor[0]).start()
                        && matcher.end() <= deniedBracketedReferences.get(cursor[0]).end();
                return !nested
                    ? resolveSecretValue(secretReplacer, matcher, resolutionsByName)
                    : matcher.group();
              });
    }
    return input;
  }

  private static String resolveTruncatingBracketsFully(
      String input,
      Function<String, String> secretReplacer,
      Map<String, String> resolutionsByName) {
    for (int i = 0; i < MAX_TRUNCATING_BRACKET_CHAIN_DEPTH; i++) {
      String next =
          replaceTokens(
              input,
              SECRET_PATTERN_PARENTHESES,
              matcher ->
                  isTruncatedByBarePattern(matcher)
                      ? resolveSecretValue(secretReplacer, matcher, resolutionsByName)
                      : matcher.group());
      if (next.equals(input)) {
        return next;
      }
      input = next;
    }
    return input;
  }

  private static boolean isTruncatedByBarePattern(MatchResult bracketedMatch) {
    String name = bracketedMatch.group("secret").trim();
    return !BARE_SECRET_NAME.matcher(name).matches();
  }

  private static boolean isDenied(
      MatchResult bracketedMatch,
      Function<String, String> secretReplacer,
      Map<String, String> resolutionsByName) {
    String name = bracketedMatch.group("secret").trim();
    return resolve(name, secretReplacer, resolutionsByName) == null;
  }

  private static String resolveSecretValue(
      Function<String, String> secretReplacer,
      Matcher matcher,
      Map<String, String> resolutionsByName) {
    var secretName = matcher.group("secret").trim();
    if (!secretName.isBlank() && !secretName.isEmpty()) {
      var result = resolve(secretName, secretReplacer, resolutionsByName);
      if (result != null) {
        return result;
      } else {
        return matcher.group();
      }
    } else {
      return null;
    }
  }

  // A plain computeIfAbsent would re-invoke secretReplacer for every denied name (Map treats a
  // null result as "still absent"), defeating the memoization this exists for.
  private static String resolve(
      String name, Function<String, String> secretReplacer, Map<String, String> resolutionsByName) {
    if (resolutionsByName.containsKey(name)) {
      return resolutionsByName.get(name);
    }
    String result = secretReplacer.apply(name);
    resolutionsByName.put(name, result);
    return result;
  }

  public static List<String> retrieveSecretKeysInInput(String input) {
    if (Objects.isNull(input)) {
      return List.of();
    }
    List<MatchResult> bracketedReferences =
        SECRET_PATTERN_PARENTHESES.matcher(input).results().toList();
    return Stream.of(SECRET_PATTERN_PARENTHESES, SECRET_PATTERN_SECRETS)
        .flatMap(
            pattern ->
                pattern
                    .matcher(input)
                    .results()
                    .filter(
                        result ->
                            pattern != SECRET_PATTERN_SECRETS
                                || isNotNestedInAny(result, bracketedReferences)))
        .map(matchResult -> matchResult.group("secret").trim())
        .distinct()
        .toList();
  }

  /**
   * A bare {@code secrets.NAME} match nested inside a {@code {{secrets.NAME}}} occurrence is not a
   * second, independent declaration — it is the bare pattern's narrower character class re-reading
   * the same literal text and stopping short at a character the bracket form tolerates (e.g. {@code
   * :}). Left in, a model declaring only {@code {{secrets.LONG:SUFFIX}}} would also admit the
   * truncated "LONG" into the allow-list, letting a runtime value spell that shorter name and
   * resolve a secret the model never declared.
   */
  private static boolean isNotNestedInAny(MatchResult candidate, List<MatchResult> outerMatches) {
    return outerMatches.stream()
        .noneMatch(outer -> candidate.start() >= outer.start() && candidate.end() <= outer.end());
  }

  public static String replaceTokens(
      String original, Pattern pattern, Function<Matcher, String> converter) {
    int lastIndex = 0;
    StringBuilder output = new StringBuilder();
    Matcher matcher = pattern.matcher(original);
    while (matcher.find()) {
      output.append(original, lastIndex, matcher.start()).append(converter.apply(matcher));
      lastIndex = matcher.end();
    }
    if (lastIndex < original.length()) {
      output.append(original, lastIndex, original.length());
    }
    return output.toString();
  }
}
