# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: meta
  hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
-   repo: local
    hooks:
      - id: license-check
        language: system
        name: License Check
        entry: bash -c 'mvn license:check; rc=$?; if [[ $rc -ne 0 ]]; then mvn license:format &>/dev/null; echo "Invalid License found and fixed"; fi; exit $rc'
        # By default, hooks will receive a list of changed files.
        # However, this doesn't integrate well with Maven plugins,
        # which operate on the entire project.
        # Therefore, we prevent pre-commit from passing changed files to the hook and
        # always run it anyway
        always_run: true
        files: ^$
      - id: spotless
        language: system
        name: Spotless
        entry: bash -c 'mvn spotless:check; rc=$?; if [[ $rc -ne 0 ]]; then mvn spotless:apply &>/dev/null; echo "Files were reformatted"; fi; exit $rc'
        always_run: true
        files: ^$
- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 41.116.8
  hooks:
    - id: renovate-config-validator
      args: [--strict]
