<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.camunda.connector</groupId>
    <artifactId>connectors-bundle-parent</artifactId>
    <version>8.10.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>element-template-generator-parent</artifactId>
  <packaging>pom</packaging>

  <name>Element Template Generator</name>
  <description>Element template generator root</description>
  <inceptionYear>2023</inceptionYear>

  <url>https://github.com/camunda/connectors</url>

  <scm>
    <connection>scm:git:git@github.com:camunda/connectors.git</connection>
    <developerConnection>scm:git:git@github.com:camunda/connectors.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/camunda/connectors</url>
  </scm>

  <developers>
    <developer>
      <id>camunda.org</id>
      <name>Camunda</name>
      <organization>Camunda Services GmbH</organization>
      <organizationUrl>https://www.camunda.com</organizationUrl>
    </developer>
  </developers>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <modules>
    <module>annotations</module>
    <module>congen-cli</module>
    <module>core</module>
    <module>maven-plugin</module>
    <module>http-dsl</module>
    <module>openapi-parser</module>
    <module>postman-collections-parser</module>
    <module>uniquet</module>
    <module>validator</module>
  </modules>

</project>