---
apiVersion: v2
name: preview-environments
appVersion: dev
description: A Helm chart to deploy a C8 Connectors preview environment to the Camunda-CI cluster managed by the Infrastructure team.
icon: https://console.cloud.camunda.io/favicon.ico
type: application
# Chart version; expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

dependencies:
- name: infra-preview-environments-ingress
  repository: oci://registry.camunda.cloud/library
  version: 1.4.1
- name: camunda-platform
  # @camunda-cloud references https://helm.camunda.io repository configured as camunda-cloud in Argo CD
  repository: https://helm.camunda.io
  version: 9.3.5
