/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH
 * under one or more contributor license agreements. Licensed under a proprietary license.
 * See the License.txt file for more information. You may not use this file
 * except in compliance with the proprietary license.
 */
package io.camunda.connector.agenticai.a2a.client.outbound.model;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import io.camunda.connector.agenticai.model.AgenticAiRecord;
import io.camunda.connector.api.annotation.FEEL;
import io.camunda.connector.api.document.Document;
import io.camunda.connector.generator.java.annotation.FeelMode;
import io.camunda.connector.generator.java.annotation.TemplateProperty;
import jakarta.validation.constraints.NotBlank;
import java.util.List;
import javax.annotation.Nullable;

@AgenticAiRecord
@JsonDeserialize(
    builder =
        A2aSendMessageOperationParameters.A2aSendMessageOperationParametersJacksonProxyBuilder
            .class)
public record A2aSendMessageOperationParameters(
    @NotBlank
        @FEEL
        @TemplateProperty(
            group = "operation",
            label = "Text",
            description = "The text to to be included in the message.",
            type = TemplateProperty.PropertyType.Text,
            feel = FeelMode.optional)
        String text,
    @Nullable
        @TemplateProperty(
            group = "operation",
            label = "Context ID",
            description = "The context ID for this message, used to group related interactions.",
            tooltip =
                "Context IDs are generated by the remote server. Omit if this is the first message or if this message starts a new context.",
            feel = FeelMode.optional,
            optional = true)
        String contextId,
    @Nullable
        @TemplateProperty(
            group = "operation",
            label = "Task ID",
            description = "The ID of the task this message is part of.",
            tooltip =
                "Task IDs are generated by the remote server. Omit if the message is not yet part of a specific task.",
            feel = FeelMode.optional,
            optional = true)
        String taskId,
    @FEEL
        @TemplateProperty(
            group = "operation",
            label = "Reference Task IDs",
            description = "A list of task IDs that this message references for additional context.",
            feel = FeelMode.required,
            optional = true)
        List<String> referenceTaskIds,
    @FEEL
        @TemplateProperty(
            group = "operation",
            label = "Documents",
            description = "Documents to be included in the message.",
            // TODO: add link to documentation
            tooltip = "Referenced documents that will be added to the message.",
            feel = FeelMode.required,
            optional = true)
        List<Document> documents) {

  public static A2aSendMessageOperationParametersBuilder builder() {
    return new A2aSendMessageOperationParametersBuilder();
  }

  @JsonPOJOBuilder(withPrefix = "")
  public static class A2aSendMessageOperationParametersJacksonProxyBuilder
      extends A2aSendMessageOperationParametersBuilder {}
}
