logging.level.root=info
logging.level.io.camunda.process.test=info
logging.level.org.testcontainers=warn
logging.level.tc=warn
logging.level.io.camunda.connector=debug

camunda.process-test.runtime-mode=shared
camunda.process-test.camunda-docker-image-version=SNAPSHOT