---
name: Check for PR conflicts

on:
  schedule:
  - cron: 23 1 * * 1-5
  workflow_dispatch:

jobs:
  check-pr-conflicts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
    - name: Check all PRs for conflict
      uses: camunda/infra-global-github-actions/preview-env/conflicts@main
