---
name: Check for PR conflicts

on:
  schedule:
  - cron: 23 1 * * 1-5
  workflow_dispatch:

jobs:
  check-pr-conflicts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
    - name: Check all PRs for conflict
      uses: camunda/infra-global-github-actions/preview-env/conflicts@main
