---
name: Check for PR conflicts

on:
  schedule:
  - cron: 23 1 * * 1-5
  workflow_dispatch:

jobs:
  check-pr-conflicts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Check all PRs for conflict
      uses: camunda/infra-global-github-actions/preview-env/conflicts@main
