name: E2E test run

on:
  workflow_dispatch:
  schedule: # Run nightly
    - cron: "0 3 * * *"  # Runs daily at 03:00 UTC
  pull_request:
    types: [ labeled, synchronize ]

jobs:

  setup:
    runs-on: ubuntu-latest
    # Only run if scheduled/manual OR if the 'e2e-tests' label exists on a non-fork PR
    if: |
      github.event_name != 'pull_request' ||
      (github.event.pull_request.head.repo.fork == false &&
       (github.event.action == 'labeled' && github.event.label.name == 'e2e-tests') ||
       (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'e2e-tests')))
    outputs:
      branches: ${{ steps.set-branches.outputs.branches }}
    steps:
      - name: Fetch stable branches
        id: set-branches
        run: |
          git ls-remote --heads https://github.com/${{ github.repository }}.git | \
          awk '{print $2}' | sed 's|refs/heads/||' | grep '^stable/' > stables.txt || true
          all_branches=$( (echo "main"; cat stables.txt) | grep -v '^$' | jq -R -s -c 'split("\n")[:-1]' )
          echo "branches=$all_branches" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-e2e-tests:
    name: (${{ matrix.branch }})
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(needs.setup.outputs.branches) }}
    uses: ./.github/workflows/E2E_BRANCH_RUN.yml
    with:
      branch: ${{ matrix.branch }}
    secrets: inherit
