name: Refresh Merge Queue Status

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to refresh in merge queue'
        required: true
        type: string

jobs:
  refresh-merge-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        id: vault-secrets
        uses: hashicorp/vault-action@v3.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID}}
          secrets: |
            secret/data/products/connectors/ci/common GITHUB_APP_ID;
            secret/data/products/connectors/ci/common GITHUB_APP_PRIVATE_KEY;
      
      - name: Generate a GitHub token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ steps.vault-secrets.outputs.GITHUB_APP_ID }}
          private-key: ${{ steps.vault-secrets.outputs.GITHUB_APP_PRIVATE_KEY }}
      
      - name: Refresh PR Status to Unblock Merge Queue
        uses: actions/github-script@v8
        with:
          script: |
            const prNumber = ${{ github.event.inputs.pr_number }};
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;
            
            console.log(`Refreshing merge queue status for PR #${prNumber}`);
            
            // Get PR details
            const { data: pr } = await github.rest.pulls.get({
              owner: repoOwner,
              repo: repoName,
              pull_number: prNumber,
            });
            
            console.log(`PR #${prNumber}: ${pr.title}`);
            console.log(`Status: ${pr.state}, Mergeable: ${pr.mergeable}, Mergeable state: ${pr.mergeable_state}`);
            
            // Create a neutral status check to refresh the queue
            await github.rest.repos.createCommitStatus({
              owner: repoOwner,
              repo: repoName,
              sha: pr.head.sha,
              state: "success",
              context: "merge-queue-refresh",
              description: `Merge queue status refreshed at ${new Date().toISOString()}`,
            });
            
            console.log(`Successfully refreshed status for PR #${prNumber}`);
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}