name: Test branch

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.7.1
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false # we rely on step outputs, no need for environment variables
          secrets: |
            secret/data/products/connectors/ci/common ARTIFACTORY_USR;
            secret/data/products/connectors/ci/common ARTIFACTORY_PSW;

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Use CI Nexus as co-located pull-through cache for Maven artifacts via ~/.m2/settings.xml
      - name: 'Create settings.xml'
        uses: s4u/maven-settings-action@v2.8.0
        with:
          githubServer: false
          servers: |
            [{
               "id": "camunda-nexus",
               "username": "${{ steps.secrets.outputs.ARTIFACTORY_USR }}",
               "password": "${{ steps.secrets.outputs.ARTIFACTORY_PSW }}"
             }]
          mirrors: '[{"url": "https://repository.nexus.camunda.cloud/content/groups/internal/", "id": "camunda-nexus", "mirrorOf": "camunda-nexus", "name": "camunda Nexus"}]'

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build Connectors
        run: mvn --batch-mode clean verify -PcheckFormat

      - name: Lint Dockerfile - connector-runtime
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: connector-runtime/connector-runtime-application/Dockerfile

      - name: Lint Dockerfile - SaaS
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: bundle/camunda-saas-bundle/Dockerfile

      - name: Lint Dockerfile - default-bundle
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: bundle/default-bundle/Dockerfile
